import 'package:label_core/label_core.dart';
import 'package:label_history/label_history.dart';
import 'package:mobx/mobx.dart';

import 'document_store.dart';
import 'history_store.dart';

part 'layer_store.g.dart';

/// Order, visibility and lock state of a [LabelDocument]'s layers.
///
/// Edits go through [HistoryStore] via [ChangeDocumentCommand], the same
/// way [PropertyStore] edits elements — layers are undo-able too, since
/// they're as much a part of the document as the elements on them.
class LayerStore = LayerStoreBase with _$LayerStore;

abstract class LayerStoreBase with Store {
  LayerStoreBase(this._documentStore, this._historyStore);

  final DocumentStore _documentStore;
  final HistoryStore _historyStore;

  /// Layers in paint order (back to front).
  @computed
  List<LabelLayer> get layers =>
      [...(_documentStore.layers)]..sort((a, b) => a.order.compareTo(b.order));

  /// The elements placed on [layerId], in their current z-order.
  List<LabelElement> elementsOf(String layerId) => _documentStore.elements
      .where((element) => element.layerId == layerId)
      .toList();

  @action
  void setVisible(String layerId, {required bool visible}) =>
      _updateLayer(layerId, (layer) => layer.copyWith(visible: visible));

  @action
  void setLocked(String layerId, {required bool locked}) =>
      _updateLayer(layerId, (layer) => layer.copyWith(locked: locked));

  @action
  void reorder(String layerId, int newOrder) =>
      _updateLayer(layerId, (layer) => layer.copyWith(order: newOrder));

  /// Adds a new layer on top of every existing one (highest `order`).
  /// [id] is generated by the caller (`label_designer`'s
  /// `generateLayerId`) — stores never generate ids themselves, same
  /// convention `HistoryStore.addElement` already follows for elements.
  @action
  void addLayer({required String id, String? name}) {
    final oldLayers = _documentStore.document.layers;
    final nextOrder = oldLayers.isEmpty
        ? 0
        : oldLayers.map((layer) => layer.order).reduce((a, b) => a > b ? a : b) +
              1;
    final newLayer = LabelLayer(
      id: id,
      name: name ?? 'Camada ${oldLayers.length + 1}',
      order: nextOrder,
    );
    _historyStore.execute(
      ChangeDocumentCommand<List<LabelLayer>>(
        oldValue: oldLayers,
        newValue: [...oldLayers, newLayer],
        apply: (document, value) => document.copyWith(layers: value),
      ),
    );
  }

  /// Whether [layerId] can be removed — a document must always keep at
  /// least one layer.
  bool canRemoveLayer(String layerId) => _documentStore.document.layers.length > 1;

  /// Removes [layerId] and every element placed on it (see
  /// [elementsOf]), as a single undo step — a layer's elements can't be
  /// left referencing a `layerId` that no longer exists. No-ops if
  /// [layerId] is the only layer left; see [canRemoveLayer].
  @action
  void removeLayer(String layerId) {
    if (!canRemoveLayer(layerId)) return;
    final oldLayers = _documentStore.document.layers;
    final oldElements = _documentStore.document.elements;
    _historyStore.execute(
      ChangeDocumentCommand<({List<LabelLayer> layers, List<LabelElement> elements})>(
        oldValue: (layers: oldLayers, elements: oldElements),
        newValue: (
          layers: oldLayers.where((l) => l.id != layerId).toList(),
          elements: oldElements.where((e) => e.layerId != layerId).toList(),
        ),
        apply: (document, value) =>
            document.copyWith(layers: value.layers, elements: value.elements),
      ),
    );
  }

  void _updateLayer(
    String layerId,
    LabelLayer Function(LabelLayer layer) update,
  ) {
    final oldLayers = _documentStore.document.layers;
    final newLayers = [
      for (final layer in oldLayers)
        layer.id == layerId ? update(layer) : layer,
    ];
    _historyStore.execute(
      ChangeDocumentCommand<List<LabelLayer>>(
        oldValue: oldLayers,
        newValue: newLayers,
        apply: (document, value) => document.copyWith(layers: value),
      ),
    );
  }
}
