import 'package:equatable/equatable.dart';

/// Bookkeeping information about a [LabelDocument], separate from its
/// visual content.
class DocumentMetadata extends Equatable {
  const DocumentMetadata({
    this.author,
    required this.createdAt,
    required this.updatedAt,
    this.thumbnailBase64,
    this.history = const [],
  });

  factory DocumentMetadata.fromJson(Map<String, dynamic> json) {
    return DocumentMetadata(
      author: json['author'] as String?,
      createdAt: DateTime.parse(json['createdAt'] as String),
      updatedAt: DateTime.parse(json['updatedAt'] as String),
      thumbnailBase64: json['thumbnail'] as String?,
      history: (json['history'] as List<dynamic>? ?? [])
          .map((entry) => entry as String)
          .toList(),
    );
  }

  final String? author;
  final DateTime createdAt;
  final DateTime updatedAt;

  /// PNG thumbnail encoded as base64, generated by `label_renderer_canvas`
  /// when the document is saved. `null` until first save.
  final String? thumbnailBase64;

  /// Free-form save log, e.g. `"v1 salvo por fulano em 2026-07-02"`.
  /// This is a persisted audit trail, distinct from the in-memory
  /// undo/redo stack owned by `label_history` at edit time.
  final List<String> history;

  DocumentMetadata copyWith({
    String? author,
    DateTime? createdAt,
    DateTime? updatedAt,
    String? thumbnailBase64,
    List<String>? history,
  }) {
    return DocumentMetadata(
      author: author ?? this.author,
      createdAt: createdAt ?? this.createdAt,
      updatedAt: updatedAt ?? this.updatedAt,
      thumbnailBase64: thumbnailBase64 ?? this.thumbnailBase64,
      history: history ?? this.history,
    );
  }

  Map<String, dynamic> toJson() => {
    if (author != null) 'author': author,
    'createdAt': createdAt.toUtc().toIso8601String(),
    'updatedAt': updatedAt.toUtc().toIso8601String(),
    if (thumbnailBase64 != null) 'thumbnail': thumbnailBase64,
    'history': history,
  };

  @override
  List<Object?> get props => [
    author,
    createdAt,
    updatedAt,
    thumbnailBase64,
    history,
  ];
}
