import 'package:equatable/equatable.dart';

/// Bookkeeping information about a [LabelDocument], separate from its
/// visual content.
class DocumentMetadata extends Equatable {
  const DocumentMetadata({
    this.author,
    required this.createdAt,
    required this.updatedAt,
    this.thumbnailBase64,
  });

  factory DocumentMetadata.fromJson(Map<String, dynamic> json) {
    return DocumentMetadata(
      author: json['author'] as String?,
      createdAt: DateTime.parse(json['createdAt'] as String),
      updatedAt: DateTime.parse(json['updatedAt'] as String),
      thumbnailBase64: json['thumbnail'] as String?,
    );
  }

  final String? author;
  final DateTime createdAt;
  final DateTime updatedAt;

  /// PNG thumbnail encoded as base64, generated by `label_renderer_canvas`
  /// when the document is saved. `null` until first save.
  final String? thumbnailBase64;

  DocumentMetadata copyWith({
    String? author,
    DateTime? createdAt,
    DateTime? updatedAt,
    String? thumbnailBase64,
  }) {
    return DocumentMetadata(
      author: author ?? this.author,
      createdAt: createdAt ?? this.createdAt,
      updatedAt: updatedAt ?? this.updatedAt,
      thumbnailBase64: thumbnailBase64 ?? this.thumbnailBase64,
    );
  }

  Map<String, dynamic> toJson() => {
    if (author != null) 'author': author,
    'createdAt': createdAt.toUtc().toIso8601String(),
    'updatedAt': updatedAt.toUtc().toIso8601String(),
    if (thumbnailBase64 != null) 'thumbnail': thumbnailBase64,
  };

  @override
  List<Object?> get props => [author, createdAt, updatedAt, thumbnailBase64];
}
